// src/pages/Login.jsx
import { useState } from "react"

function Login() {
    const [formData, setFormData] = useState({
        email: '',
        password: '',
        isTeacher: false
    });

    const handleChange = (e) => {
        const { name, value } = e.target;
        setFormData({
            ...formData,
            [name]: value
        })
    };

    const handleSubmit = (e) => {
        e.preventDefault();
        console.log("Submitted", formData);
    }

    return (
        <div>
            <div className="header">
                ACSys
            </div>
            <div>
                <form onSubmit={handleSubmit}>
                    <h2>Login</h2>
                    <label htmlFor="email">
                        <input 
                            type="email" 
                            name="email" 
                            placeholder="Email" 
                            value={formData.email}
                            onChange={handleChange}
                            required />
                    </label>
                    <label htmlFor="passowrd">
                        <input 
                            type="password" 
                            name="password" 
                            placeholder="Password" 
                            value={formData.password}
                            onChange={handleChange}
                            required />
                    </label>
                    <label htmlFor="isTeacher">
                        Are you a teacher?
                        <input 
                            type="checkbox" 
                            name="isTeacher" 
                            checked={formData.isTeacher}
                            onChange={handleChange} />
                    </label>
                    <input type="submit" value="Login" />
                </form>
            </div>
        </div>
    )
}

export default Login

// client/src/routes/login/+page.svelte
<script>
  let formData = {
    email: "",
    password: "",
    isTeacher: false,
  };

  function handleChange(event) {
    const { name, value, type, checked } = event.target;
    formData = {
      ...formData,
      [name]: type === "checkbox" ? checked : value,
    };
  }

  function handleSubmit(event) {
    event.preventDefault();
    console.log("Submitted", formData);
  }
</script>

<div>
  <div class="header">ACSys</div>
  <div>
    <form on:submit={handleSubmit}>
      <h2>Login</h2>
      <label for="email">
        <input
          type="email"
          name="email"
          placeholder="Email"
          bind:value={formData.email}
          on:input={handleChange}
          required
        />
      </label>
      <label for="password">
        <input
          type="password"
          name="password"
          placeholder="Password"
          bind:value={formData.password}
          on:input={handleChange}
          required
        />
      </label>
      <label for="isTeacher">
        Are you a teacher?
        <input
          type="checkbox"
          name="isTeacher"
          bind:checked={formData.isTeacher}
          on:change={handleChange}
        />
      </label>
      <input type="submit" value="Login" />
    </form>
  </div>
</div>
