// old/src/pages/TeacherProblemList.jsx
import { useState } from "react";
import ListEntry from "../Components/ListEntry";

const SAMPLE = [
    {
        class: "A",
        name: "Simple Operators",
        code: "simple-op"
    },
    {
        class: "A",
        name: "Conditionals",
        code: "if-else"
    },
    {
        class: "B",
        name: "Peeta and Binary Search",
        code: "bsearch"
    },
    {
        class: "C",
        name: "Tesseract and the Infinite Tsukuyomi",
        code: "tesseract"
    }
];

function TeacherProblemList() {
    const [classID, setClassID] = useState('')
    const problems = SAMPLE.filter(problem => classID === '' || problem.class.toLowerCase() === classID.toLowerCase())

    const handleClassIDChange = (e) => {
        setClassID(e.target.value)
    }

    return (
        <div>
            <div>
                <h1>ACSys | Problem List</h1>
            </div>
            <div>
                Class: 
                <input 
                    type="text" 
                    name="class" 
                    placeholder="Class ID"
                    onChange={handleClassIDChange} />
                <button>New Problem</button>
            </div>
            <div>
                {problems.map(problem => (
                    <li key={problem.code}>
                        <ListEntry 
                            name={problem.name} 
                            classID={problem.class}
                            code={problem.code}
                            isEditable={true} />
                    </li>
                ))}
            </div>
        </div>
    )
}

export default TeacherProblemList

// client/src/routes/problems/Components/TeacherProblemList.svelte
<script>
    export let problems;
    import ListEntry from "./ListEntry.svelte";

    $: console.log(problems)
  
    const SAMPLE = [
      {
        status: "Incomplete",
        class: "A",
        name: "Simple Operators",
        code: "simple-op",
      },
      {
        status: "Complete",
        class: "A",
        name: "Conditionals",
        code: "if-else",
      },
      {
        status: "Incomplete",
        class: "B",
        name: "Peeta and Binary Search",
        code: "bsearch",
      },
      {
        status: "Complete",
        class: "C",
        name: "Tesseract and the Infinite Tsukuyomi",
        code: "tesseract",
      },
    ];
  
    let classID = "";
    let shownProblems = [];

    $: shownProblems = problems.filter(
      (problem) => 
        classID === "" || problem.class.toLowerCase() === classID.toLowerCase()
    )
  
  </script>
  
  <div>
    <div class="block">
      <h1 class="text-gray-300 text-5xl p-10">
        <span class="px-5 font-bold">ACSys</span>
        <span class="px-3">Problem List</span>
      </h1>
    </div>
    <div class="flex">
      <div class="p-5">
        <span class="text-emerald-300">Class{" "}</span>
        <input
          type="text"
          name="class"
          placeholder="Class ID"
          bind:value={classID}
        />
      </div>
      <div class="my-5 px-3 rounded-xl bg-emerald-400">
        <a href="/problems/new">Add Problem</a>
      </div>
    </div>
    <div class="flex py-2 px-5 text-xl">
      <span class="text-gray-300 flex-none w-1/4">Status</span>
      <span class="text-gray-300 flex-none w-1/3">Name</span>
      <span class="text-gray-300 flex-none w-1/4">Code</span>
    </div>
    <div>
      {#each shownProblems as problem (problem.code)}
        <div>
          <ListEntry
            status={problem.status}
            name={problem.title}
            classID={problem.class_code}
            code={problem.code}
            isEditable={true}
          />
        </div>
      {/each}
    </div>
  </div>
